global.newMaterialParts = [
    /////////////// Tier 0 Metals: Overworld /////////////////////////////
    
    {
      'material': 'iron',
      'color': 0xd9d7d7,
      'type': 'base_metal',
      'tier': 0,
      'itemParts': ['plating', 'sheet'],
      'blockParts': ['cog_block'],
      'fluid_id': 'tconstruct:molten_iron',
      'ore': true,
      'byproducts': ['nickel'],
      'allomancy': 'Iron allows you to Pull on metals. For items and other small entities, this means pulling them toward you. For blocks and large metallic entities, this means you move toward them',
      'feruchemy': 'Weight--Slow + Resist or Feather Fall',
    },
    {
      'material': 'tin',
      'color': 0x9dbdc2,
      'type': 'base_metal',
      'tier': 0,
      'itemParts': ['rod', 'wire', 'plating'],
      'blockParts': [],
      'fluid_id': 'tconstruct:molten_tin',
      'ore': true,
      'byproducts': ['flourite'],
      'allomancy': 'Tin gives you Night Vision, and allows you to see which direction sounds come from using an indicator particle. This particle is also colored according to the hostility of the sound source. Friendly mobs are green, hostile mobs are red',
      'feruchemy': 'Sight--Night Vision or Blindness'
    },
    {
      'material': 'gold',
      'color': 0xf5c564,
      'type': 'base_metal',
      'tier': 0,
      'itemParts': ['plating', 'sheet'],
      'blockParts': ['cog_block'],
      'fluid_id': 'tconstruct:molten_gold',
      'ore': true,
      'byproducts': ['iron'],
      'allomancy': 'Gold lets you see into your "past" by showing you the location you most recently died in this dimension',
      'feruchemy': 'Health--Regeneration/Instant Health or Health Drains/s'
    },
    {
      'material': 'copper',
      'color': 0xfc9d65,
      'type': 'base_metal',
      'tier': 0,
      'itemParts': ['interlocking_component', 'plating', 'sheet'],
      'blockParts': ['cog_block'],
      'fluid_id': 'tconstruct:molten_copper',
      'ore': true,
      'byproducts': ['gold', 'sulfur'],
      'allomancy': 'Copper hides your Allomancy from detection. When you are burning copper, yourself and other allomancers nearby are cloaked from the senses of a Bronze burner. However, your own ability to use Bronze is nullified when burning Copper',
      'feruchemy': 'Memories--Stores Experience or Retrieved Stored Experience'
    },
    
    /////////////// Tier 1 Metals: Nether/Overworld /////////////////////////////
    {
      'material': 'lead',
      'color': 0x4f5a6e,
      'type': 'base_metal',
      'tier': 1,
      'itemParts': ['rod', 'sheet', 'plating'],
      'blockParts': [],
      'fluid_id': 'tconstruct:molten_lead',
      'ore': true,
      'byproducts': ['silver'],
    },
    {
      'material': 'silver',
      'color': 0xc7d3d6,
      'type': 'base_metal',
      'tier': 1,
      'itemParts': ['rod', 'wire', 'sheet'],
      'blockParts': [],
      'fluid_id': 'tconstruct:molten_silver',
      'ore': true,
      'byproducts': ['lead'],
    },
    {
      'material': 'zinc',
      'color': 0x97c7b3,
      'type': 'base_metal',
      'tier': 1,
      'itemParts': ['plate', 'gear', 'rod', 'wire'],
      'blockParts': [],
      'fluid_id': 'tconstruct:molten_zinc',
      'ore': true,
      'byproducts': ['sulfur'],
      'allomancy': 'Zinc allows you to Riot the emotions of mobs, making them hostile. This means they will attack anything nearby. Even farm animals can be a threat',
      'feruchemy': 'Mental Speed--Earn Mores/Less Experience orbs when Tapping/Storing respectively'
    },
    {
      'material': 'arcanite',
      'color': 0xe2d4fa,
      'tier': 1,
      'type': 'base_metal',
      'itemParts': ['ingot', 'nugget', 'dust'],
      'blockParts': ['storage_block'],
      'ore': true,
      'raw_ore': true
    },
    
    /////////////// Tier 2 Metals /////////////////////////////
    {
      'material': 'cobalt',
      'color': 0x2e5cd1,
      'type': 'base_metal',
      'tier': 2,
      'itemParts': ['plate', 'gear', 'rod', 'wire', 'interlocking_component', 'model_spool', 'model_wire_coil', 'reinforced_plating', 'sheet', 'hull_panel', 'plating', 'bolt'],
      'blockParts': ['cog_block', 'casing', 'coil', 'scaffolding', 'frame_box'],
      'ore': true,
      'fluid_id': 'tconstruct:molten_cobalt',
      'byproducts': ['gold', 'mithril'],
    },
    {
      'material': 'aluminum',
      'color': 0xb6c2c2,
      'type': 'base_metal',
      'tier': 2,
      'itemParts': ['plate', 'gear', 'rod', 'plating', 'sheet'],
      'blockParts': [],
      'ore': true,
      'raw_ore': true,
      'fluid_id': 'tconstruct:molten_aluminum',
      'byproducts': ['titanium'],
      'allomancy': 'Aluminum is a purifying metal - it removes all metals from your current stock. This may seem useless, but it also removes all potion effects - not a bad trade to remove some Wither or Poison before it kills you',
      'feruchemy': 'Aluminum and FID: Storing in a metalmind "Keys" it to you, so that only you can tap the power stored within. But if you Store Aluminum first, the metalmind remains "unkeyed", allowing any Feruchemist to Tap is Resouces (good for Co-ops!) (Note this makes the metalmind unable to be keyed, even if all charges are removed)'
    },
    {
      'material': 'mithril',
      'color': 0x8a90db,
      'tier': 2,
      'type': 'base_metal',
      'itemParts': ['ingot', 'nugget','dust'],
      'blockParts': ['storage_block'],
      'ore': true,
      'raw_ore': true,
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_mithril',
    },
    {
      'material': 'nickel',
      'color': 0xc2b17a,
      'type': 'base_metal',
      'tier': 2,
      'itemParts': ['rod', 'wire', 'sheet', 'plating'],
      'blockParts': [],
      'fluid_id': 'tconstruct:molten_nickel',
      'ore': true,
      'byproducts': ['iron', 'platinum'],
    },
    
    
    /////////////// Tier 3 Metals: The End /////////////////////////////
    
    {
      'material': 'titanium',
      'color': 0x4668cf,
      'type': 'base_metal',
      'tier': 3,
      'itemParts': ['plate', 'gear', 'rod', 'plating', 'sheet', 'bolt'],
      'blockParts': ['casing', 'scaffolding', 'frame_box'],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_titanium',
      'ore': true,
      'raw_ore': true,
      'byproducts': ['aluminum'],
    }, 
    {
      'material': 'uranium',
      'color': 0x8be8b0,
      'type': 'base_metal',
      'tier': 3,
      'itemParts': ['plate', 'gear', 'rod'],
      'blockParts': [],
      'ore': true,
      'fluid_id': 'tconstruct:molten_uranium',
      'byproducts': ['lead', 'thorium'],
    },
    {
      'material': 'magnesium',
      'color': 0xcfc5d4,
      'tier': 3,
      'type': 'base_metal',
      'itemParts': ['plate', 'plating'],
      'blockParts': [],
      'fluid': 'thick',
      'ore': true,
      'raw_ore': true,
    },
    {
      'material': 'aetherium',
      'color': 0x250d75,
      'tier': 3,
      'type': 'base_metal',
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'gear', 'rod', 'plating'],
      'blockParts': ['storage_block'],
      'fluid': 'thick',
      'ore': true,
      'raw_ore': true,
    },
    
    {
      'material': 'netherite_scrap',
      'color': 0x543f35,
      'tier': 3,
      'type': 'gem',
      'itemParts': ['dust'],
      'blockParts': [],
      'fluid_id': 'tconstruct:molten_debris',
    },
    /////////////// Tier 4 Metals: Moon /////////////////////////////
    
    {
      'material': 'rune',
      'ore_name': 'Runite',
      'color': 0x73b4bf,
      'type': 'base_metal',
      'tier': 4,
      'itemParts': ['ingot', 'nugget', 'dust'],
      'blockParts': ['storage_block'],
      'ore': true,
      'raw_ore': true
    },   
    {
      'material': 'osmium',
      'color': 0xe6f7ff,
      'type': 'base_metal',
      'tier': 4,
      'itemParts': ['plate', 'gear', 'rod', 'plating'],
      'blockParts': ['cog_block'],
      'ore': true,
      'byproducts': ['silver', 'platinum', 'manganese'],
    },
    {
      'material': 'platinum',
      'color': 0x91ecff,
      'type': 'base_metal',
      'tier': 4,
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'gear', 'rod', 'plating'],
      'blockParts': ['storage_block', 'cog_block'],
      'ore': true,
      'raw_ore': true,
      'byproducts': ['nickel', 'osmium', 'chromium'],
    },
    {
      'material': 'desh',
      'color': 0xffa34d,
      'type': 'base_metal',
      'tier': 4,
      'itemParts': ['gear', 'rod', 'dust', 'wire', 'model_spool', 'model_wire_coil'],
      'blockParts': ['coil'],
      'ore': true
    },
    /////////////// Tier 5 Metals: Mars /////////////////////////////

    //{
    //  'material': 'stellarite',
    //  'color': 0x858f7c,
    //  'tier': 5,
    //  'type': 'base_metal',
    //  'itemParts': ['ingot', 'gear', 'rod', 'dust', 'plating'],
    //  'blockParts': [],
    //  'ore': true,
    //  'raw_ore': true
    //},
    {
      'material': 'tungsten',
      'color': 0x282c33,
      'type': 'base_metal',
      'tier': 5,
      'itemParts': ['plate', 'gear', 'rod', 'plating', 'reinforced_plating', 'wire', 'model_spool', 'model_wire_coil'],
      'blockParts': ['coil'],
      'ore': true,
      'raw_ore': true,
      'byproducts': ['thorium'],
    },
    {
      'material': 'orichalcum',
      'color': 0xfa6837,
      'tier': 5,
      'type': 'base_metal',
      'itemParts': ['ingot', 'nugget','dust', 'rod', 'ring', 'sprocket'],
      'blockParts': ['storage_block'],
      'ore': true,
      'raw_ore': true,
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_orichalcum',
    },
    {
      'material': 'ostrum',
      'color': 0x73485d,
      'tier': 5,
      'type': 'base_metal',
      'itemParts': ['gear', 'rod', 'dust', 'plate'],
      'blockParts': [],
      'ore': true,
    },
    {
      'material': 'cadmium',
      'color': 0x97b7bf,
      'type': 'base_metal',
      'tier': 5,
      'itemParts': ['ingot', 'plate',  'gear', 'rod', 'dust', 'wire', 'model_spool'],
      'blockParts': ['storage_block'],
      'fluid': 'thick',
      'ore': true,
      'raw_ore': true,
      'allomancy': 'Cadmium slows down the mobs in the area around you',
      'feruchemy': 'Breath--Respiration/Water Breathing or Air Bar when not swimming',
    },

    /////////////// Tier 6 Metals: Venus /////////////////////////////
    {
      'material': 'iridium',
      'color': 0x1942bf,
      'type': 'base_metal',
      'tier': 6,
      'itemParts': ['plate',  'gear', 'rod'],
      'blockParts': [],
      'fluid': 'thick',
      'ore': true,
      'raw_ore': true
    },
    {
      'material': 'palladium',
      'color': 0x4f2237,
      'type': 'base_metal',
      'tier': 6,
      'itemParts': ['plate',  'gear', 'rod'],
      'blockParts': [],
      'fluid': 'thick',
      'ore': true,
      'raw_ore': true
    },
    {
      'material': 'adamantium',
      'ore_name': 'Adamantite',
      'color': 0xc23c3c,
      'tier': 6,
      'type': 'base_metal',
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'gear', 'rod', 'wire', 'model_spool', 'model_wire_coil'],
      'blockParts': ['storage_block', 'coil'],
      'ore': true,
      'raw_ore': true
    },
    {
      'material': 'calorite',
      'color': 0xc43b3b,
      'tier': 6,
      'type': 'base_metal',
      'itemParts': ['gear', 'rod', 'dust', 'plate'],
      'blockParts': [],
      'ore': true,
    },

    /////////////// Tier 7 Metals: Glacio /////////////////////////////
    
    {
      'material': 'vibranium',
      'color': 0x7cebbe,
      'tier': 7,
      'type': 'base_metal',
      'itemParts': ['ingot', 'nugget','dust', 'plate', 'gear', 'rod', 'interlocking_component','reinforced_plating', 'sheet', 'hull_panel', 'plating', 'bolt', 'wire', 'model_spool', 'model_wire_coil', 'model_dual_coil', 'model_part_bundle'],
      'blockParts': ['storage_block', 'coil'],
      'ore': true,
      'raw_ore': true,
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_vibranium',
    },
    {
      'material': 'uru',
      'color': 0x1c121c,
      'tier': 7,
      'type': 'base_metal',
      'itemParts': ['ingot', 'nugget','dust', 'plate', 'gear', 'rod', 'reinforced_plating', 'sheet', 'hull_panel', 'plating', 'bolt'/*, 'wire', 'model_spool', 'model_wire_coil', */],
      'blockParts': ['storage_block'],
      'ore': true,
      'raw_ore': true,
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_uru',
    },
    {
      'material': 'draconium',
      'ore_name': 'Dracolith',
      'color': 0x421c63,
      'tier': 7,
      'type': 'base_metal',
      'itemParts': ['ingot', 'nugget','dust', 'plate', 'gear', 'rod', 'reinforced_plating', 'sheet', 'hull_panel', 'plating', 'bolt'/*, 'wire', 'model_spool', 'model_wire_coil', */],
      'blockParts': ['storage_block'],
      'ore': true,
      'raw_ore': true,
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_draconium',
    },
    ///////////////// Tier 8 Metals: Glacio /////////////////////////////


    /////////////// Rare Metals /////////////////////////////
    
    {
      'material': 'thorium',
      'color': 0x452852,
      'type': 'rare_metal',
      'tier': 3,
      'itemParts': ['plate', 'rod', 'gear'],
      'blockParts': [],
      'ore': true,
      //'raw_ore': true,
      'byproducts': ['lead'],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_thorium',
    },
    {
      'material': 'manganese',
      'color': 0xb5c7a1,
      'type': 'rare_metal',
      'tier': 4,
      'itemParts': [],
      'blockParts': [],
      'fluid': 'thick',
      'ore': true,
      //'raw_ore': true,
    },
    {
      'material': 'chromium',
      'color': 0xcfb793,
      'type': 'rare_metal',
      'tier': 4,
      'itemParts': ['plate', 'gear', 'rod', 'dust', 'ingot'],
      'blockParts': [],
      'fluid': 'thick',
      'allomancy': 'Chromium removes all metals from the stock of players you click on, while also removing all potion effects from them',
      'feruchemy': 'Luck--Good or Bad Luck',
      'ore': true,
    },
    {
      'material': 'lithium',
      'color': 0xab4154,
      'type': 'rare_metal',
      'tier': 4,
      'itemParts': ['plating'],
      'blockParts': [],
      'ore': true,
    },
    {
      'material': 'beryllium',
      'color': 0x3C894B,
      'type': 'base_metal',
      'tier': 5,
      'itemParts': ['wire', 'model_spool'],
      'blockParts': [],
    },
    {
      'material': 'molybdenum',
      'color': 0x78c4b6,
      'type': 'rare_metal',
      'tier': 5,
      'itemParts': ['plate', 'gear', 'rod'],
      'blockParts': [],
      'fluid': 'thick',
      'ore': true,
      //'raw_ore': true,
    },
    {
      'material': 'boron',
      'color': 0x20293b,
      'tier': 5,
      'itemParts': ['ingot', 'nugget', 'dust'],
      'blockParts': ['storage_block'],
      'fluid': 'thick',
      'ore': true,
    },
    {
      'material': 'scandium',
      'color': 0xd4d2bc,
      'type': 'rare_metal',
      'tier': 6,
      'itemParts': [],
      'blockParts': [],
      'ore': true,
      //'raw_ore': true,
    },
    {
      'material': 'vanadium',
      'color': 0x464e66,
      'type': 'rare_metal',
      'tier': 7,
      'itemParts': ['plate', 'gear', 'rod'],
      'blockParts': [],
      'ore': true,
      //'raw_ore': true,
    },
    {
      'material': 'neodymium',
      'color': 0x634d59,
      'type': 'rare_metal',
      'tier': 7,
      'itemParts': ['plate', 'gear', 'rod'],
      'blockParts': [],
      'fluid': 'thick',
      'ore': true,
      //'raw_ore': true,
    },



    /////////////// Tier 1 Alloys: Create Mixer /////////////////////////////
    {
      'material': 'bronze',
      'color': 0xfa7532,
      'type': 'alloy',
      'tier': 1,
      'itemParts': ['rod', 'wire', 'sheet', 'plating'],
      'blockParts': ['sheetmetal', 'cog_block', 'casing'],
      'fluid_id': 'tconstruct:molten_bronze',
      'amount': 4,
      'dust_input': ['3x #forge:dusts/copper','#forge:dusts/tin'],
      'ingot_input': ['3x #forge:ingots/copper','#forge:ingots/tin'],
      'tinkers_input': [{tag: 'forge:molten_copper',amount: 270},{tag: 'forge:molten_tin',amount: 90}],
      'allomancy': 'Bronze allows you to detect the Allomancy of other players, in much the same way Iron or Steel detects metal or Tin indicates sounds',
      'feruchemy': 'Wakefulness--Reset Phantom Timer/Switch Day to night or Night to Day or Spawn Phantoms within ~30 of storage (Must store the whole time)'
    },
    {
      'material': 'electrum',
      'color': 0xe6db95,
      'type': 'alloy',
      'tier': 1,
      'itemParts': ['plating', 'model_wire_coil', 'sheet'],
      'blockParts': [],
      'fluid_id': 'tconstruct:molten_electrum',
      'amount': 2,
      'dust_input': ['#forge:dusts/silver', '#forge:dusts/gold'],
      'ingot_input': ['#forge:ingots/silver', '#forge:ingots/gold'],
      'tinkers_input': [{tag: 'forge:molten_gold',amount: 90},{tag: 'forge:molten_silver',amount: 90}],
      'allomancy': 'Electrum lets you see your "future", showing you the location of your current spawn point',
      'feruchemy': 'Determination--Gain bonus Hearts or STOP Regenerating'
    },
    {
      'material': 'brass',
      'color': 0xffc96b,
      'type': 'alloy',
      'tier': 1,
      'itemParts': ['gear', 'wire', 'dust', 'plating'],
      'blockParts': ['cog_block', 'casing'],
      'fluid_id': 'tconstruct:molten_brass',
      'amount': 3,
      'dust_input': ['2x #forge:dusts/copper','#forge:dusts/zinc'],
      'ingot_input': ['2x #forge:ingots/copper','#forge:ingots/zinc'],
      'tinkers_input': [{tag: 'forge:molten_copper',amount: 180},{tag: 'forge:molten_zinc',amount: 90}],
      'allomancy': 'Brass allows you to Soothe the emotions of mobs, making them passive, even fearful. Creepers are your buddies!',
      'feruchemy': 'Warmth--Melt Snow + Ice/Makes all attacks have Fire Aspect or Fire Resistance'
    },
    {
      'material': 'red_alloy',
      'color': 0xff2626,
      'type': 'alloy',
      'tier': 1,
      'itemParts': ['plate', 'gear', 'wire', 'dust', 'rod', 'model_spool','model_wire_coil', 'model_dual_coil', 'model_part_bundle'],
      'blockParts': [],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_red_alloy',
      'amount': 2,
      'dust_input': ['#forge:dusts/copper','3x #forge:dusts/redstone'],
      'ingot_input': ['#forge:ingots/copper','3x #forge:dusts/redstone'],
      'tinkers_input': [{tag: 'forge:molten_copper',amount: 90},{tag: 'forge:redstone',amount: 300}]
    },/*
    {
      'material': 'pewter',
      'color': 0x9d96b5,
      'type': 'alloy',
      'tier': 1,
      'itemParts': ['ingot', 'dust', 'nugget'],
      'blockParts': ['storage_block'],
      'fluid_id': 'tconstruct:molten_pewter',
      'amount': 4,
      'dust_input': ['2x #forge:dusts/tin','#forge:dusts/silver','#forge:dusts/lead'],
      'ingot_input': ['2x #forge:ingots/tin','#forge:ingots/silver','#forge:ingots/lead'],
      'tinkers_input': [{tag: 'forge:molten_tin',amount: 180},{tag: 'forge:molten_silver',amount: 90},{tag: 'forge:molten_lead',amount: 90}],
      'allomancy': 'Pewter grants increased speed, jump height, damage, and damage resistance to the player. Be careful, though - Any damage incurred while burning pewter is remembered, and if you stop burning it at the wrong time you could end up being killed by all the built up damage.',
      'feruchemy': 'Strength--Haste/Strength or Weakness/Mining Fatigue'
    },*/
    {
      'material': 'auric_gold',
      'color': 0xf2f274,
      'type': 'alloy',
      'tier': 1,
      'itemParts': ['ingot', 'dust', 'nugget'],
      'blockParts': ['storage_block'],
      'amount': 1,
      'dust_input': ['#forge:dusts/arcanite',['naturesaura:gold_powder','naturesaura:gold_leaf']],
      'ingot_input': ['#forge:ingots/arcanite',['naturesaura:gold_powder','naturesaura:gold_leaf']],
      },
      //{
      //  'material': 'cast_iron',
      //  'color': 0x454545,
      //  'type': 'alloy',
      //  'tier': 1,
      //  'itemParts': ['ingot', 'nugget', 'plate', 'rod', 'gear'],
      //  'blockParts': ['storage_block'],
      //},
      {
        'material': 'dielectric_alloy',
        'color': 0x2b2b2b,
        'tier': 1,
        'type': 'alloy',
        'itemParts': ['ingot', 'dust', 'gear', 'plate'],
        'blockParts': ['scaffolding'],
        'dust_input': ['#forge:dusts/red_alloy', '2x powah:dielectric_paste'],
        'ingot_input': ['#forge:ingots/red_alloy', '2x powah:dielectric_paste'],
        'amount': 2,
      },
      {
        'material': 'drenched_arcanite',
        'color': 0xb1f0fc,
        'tier': 1,
        'type': 'magic_alloy',
        'itemParts': ['rod', 'gear', 'plate', 'dust'],
        'blockParts': [],
        'fluid': 'thick',
        'fluid_id': 'kubejs:molten_drenched_arcanite',
      },
    /////////////// Tier 2 Alloys: Tinkers or chapter 2 /////////////////////////////
    
    {
      'material': 'constantan',
      'color': 0xe8a156,
      'type': 'alloy',
      'tier': 2,
      'itemParts': ['rod', 'wire', 'plating', 'model_spool', 'model_wire_coil', 'sheet'],
      'blockParts': ['cog_block', 'coil'],
      'fluid_id': 'tconstruct:molten_constantan',
      'amount': 2,
      'dust_input': ['#forge:dusts/copper','#forge:dusts/nickel'],
      'ingot_input': ['#forge:ingots/copper','#forge:ingots/nickel'],
      'tinkers_input': [{tag: 'forge:molten_copper',amount: 90},{tag: 'forge:molten_nickel',amount: 90}]
    },
    {
      'material': 'invar',
      'color': 0xa4bab5,
      'type': 'alloy',
      'tier': 2,
      'itemParts': ['rod', 'wire', 'plating', 'sheet'],
      'blockParts': ['scaffolding', 'cog_block', 'casing', 'sheetmetal'],
      'fluid_id': 'tconstruct:molten_invar',
      'amount': 3,
      'dust_input': ['2x #forge:dusts/iron','#forge:dusts/nickel'],
      'ingot_input': ['2x #forge:ingots/iron','#forge:ingots/nickel'],
      'tinkers_input': [{tag: 'forge:molten_iron',amount: 180},{tag: 'forge:molten_nickel',amount: 90}]
    },
    {
      'material': 'rose_gold',
      'color': 0xffccd8,
      'tier': 2,
      'type': 'alloy',
      'itemParts': ['dust', 'plate', 'gear', 'rod','wire'],
      'blockParts': [],
      'dust_input': ['#forge:dusts/gold', '#forge:dusts/copper'],
      'ingot_input': ['#forge:ingots/gold', '#forge:ingots/copper'],
      'amount': 2,
      'fluid_id': 'tconstruct:molten_rose_gold',
      'tinkers_input': [{tag: 'forge:molten_gold',amount: 90},{tag: 'forge:molten_copper',amount: 90}],
    },
    {
      'material': 'amethyst_bronze',
      'color': 0xc58bc9,
      'tier': 2,
      'type': 'alloy',
      'itemParts': ['dust', 'plate', 'gear', 'rod',],
      'blockParts': [],
      'dust_input': ['#forge:dusts/bronze', '#forge:gems/amethyst'],
      'ingot_input': ['#forge:ingots/bronze', '#forge:gems/amethyst'],
      'amount': 2,
      'fluid_id': 'tconstruct:molten_amethyst_bronze',
      'tinkers_input': [{tag: 'forge:molten_bronze',amount: 90},{tag: 'tconstruct:molten_amethyst',amount: 100}],
    },
    {
      'material': 'steel',
      'color': 0xb5b3b3,
      'type': 'alloy',
      'tier': 2,
      'fluid_id': 'tconstruct:molten_steel',
      'itemParts': ['plate',  'gear', 'rod', 'sheet', 'plating'],
      'blockParts': ['casing'],
      'amount': 1,
      //'dust_input': ['#forge:dusts/iron',['#forge:dusts/coal','#minecraft:coals', '#forge:dusts/coal_coke', '#forge:coal_coke']],
      //'ingot_input': ['#forge:ingots/iron',['#forge:dusts/coal','#minecraft:coals', '#forge:dusts/coal_coke', '#forge:coal_coke']],
      'tinkers_input': [{tag: 'forge:molten_iron',amount: 90},{name: 'kubejs:molten_carbon',amount: 200}],
      'allomancy': 'Steel allows you to Push on metals. This means moving metal items away from you, or pushing yourself off of metal blocks. This can be used as a sort of rudimentary flight, though it is more falling with style than anything else. Steel also allows you to use the Coin Bag item. If you have gold nuggets in your inventory and are burning steel, you can use this as a ranged weapon similar to the old Beta-edition Bow. Iron nuggets can also be used, causing more damage but far less accurately',
      'feruchemy': 'Speed--Speed Boost or Slowness'
    },
    {
      'material': 'energetic_alloy',
      'color': 0xff874f,
      'type': 'alloy',
      'tier': 2,
      'itemParts': ['custom_ingot', 'dust', 'nugget', 'plate', 'gear', 'rod', 'wire', 'interlocking_component', 'plating', 'sheet', 'bolt'],
      'blockParts': ['storage_block', 'scaffolding', 'frame_box'],
      'amount': 1,
      'dust_input': ['#forge:dusts/electrum', 'kubejs:energetic_blend'],
      'ingot_input': ['#forge:ingots/electrum','kubejs:energetic_blend'],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_energetic_alloy',
    },
    {
      'material': 'vinteum',
      'color': 0x9be3fa,
      'type': 'alloy',
      'tier': 2,
      'itemParts': ['plate', 'gear', 'rod'],
      'blockParts': [],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_vinteum',
    },

    {
      'material': 'hepatizon',
      'color': 0x5e497a,
      'type': 'alloy',
      'tier': 2,
      'fluid_id': 'tconstruct:molten_hepatizon',
      'amount': 2,
      'dust_input': ['2x #forge:dusts/copper','#forge:dusts/cobalt','4x #forge:gems/quartz'],
      'ingot_input': ['2x #forge:ingots/copper','#forge:ingots/cobalt','4x #forge:gems/quartz'],
      'tinkers_input': [{tag: 'forge:molten_copper',amount: 180},{tag: 'forge:molten_cobalt',amount: 90},{tag: 'tconstruct:molten_quartz',amount: 400}],
      'itemParts': ['plate', 'gear', 'rod', 'dust', 'interlocking_component', 'wire', 'plating'],
      'blockParts': ['casing'],
    },/*
    {
      'material': 'duralumin',
      'color': 0xbbc9c1,
      'type': 'alloy',
      'tier': 2,
      'itemParts': ['ingot', 'plate', 'gear', 'plating', 'dust', 'rod'],
      'blockParts': [],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_duralumin',
      'amount': 4,
      'dust_input': ['3x #forge:dusts/aluminum','#forge:dusts/copper'],
      'ingot_input': ['3x #forge:ingots/aluminum','#forge:ingots/copper'],
      'tinkers_input': [{tag: 'forge:molten_aluminum',amount: 270},{tag: 'forge:molten_copper',amount: 90}],
      'allomancy': 'Duralumin enhances whatever other metal you are using. This may mean pushing harder with steel, speeding things up even more with Bendalloy, or even teleporting to special locations with Gold and Electrum. If this metal burns out (which it does quickly!) or is extinguished, it empties all other burning metals of their stock.',
      'feruchemy': 'Connection--Hero of the Village or Bad Omen'
    },*/
    {
      'material': 'cobalt_brass',
      'color': 0xb8af98,
      'type': 'alloy',
      'tier': 2,
      'itemParts': ['ingot', 'dust', 'nugget', 'plate', 'gear', 'rod', 'plating'],
      'blockParts': ['storage_block', 'casing', 'cog_block'],
      'amount': 6,
      'dust_input': ['4x #forge:dusts/brass', '#forge:dusts/aluminum', '#forge:dusts/cobalt'],
      'ingot_input': ['4x #forge:ingots/brass', '#forge:ingots/aluminum', '#forge:ingots/cobalt'],
      'tinkers_input': [{tag: 'forge:molten_brass',amount: 360},{tag: 'forge:molten_aluminum',amount: 90},{tag: 'forge:molten_cobalt',amount: 90}],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_cobalt_brass',
    },
    {
      'material': 'energized_steel',
      'color': 0xe0d07e,
      'type': 'alloy',
      'tier': 2,
      'itemParts': ['plate', 'rod', 'gear', 'sheet', 'dust'],
      'blockParts': [],
    },
    {
      'material': 'reinforced_electrum',
      'color': 0x9c6097,
      'type': 'alloy',
      'tier': 2,
      'itemParts': ['ingot', 'dust', 'nugget', 'plate', 'gear', 'rod'],
      'blockParts': ['storage_block', 'scaffolding'],
      'amount': 2,
      'dust_input': ['2x #forge:dusts/electrum', '#forge:dusts/cobalt'],
      'ingot_input': ['2x #forge:ingots/electrum', '#forge:ingots/cobalt'],
      'tinkers_input': [{tag: 'forge:molten_electrum',amount: 180},{tag: 'forge:molten_cobalt',amount: 90}],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_reinforced_electrum',
    },
    {
      'material': 'swift_alloy',
      'color': 0xf2c45a,
      'type': 'alloy',
      'tier': 2,
      'itemParts': ['dust', 'plate', 'gear', 'rod'],
      'blockParts': [],
      //'fluid_id': 'tconstruct:molten_manyullyn',
      //'amount': 4,
      //'dust_input': ['3x #forge:dusts/cobalt','#forge:ingots/netherite_scrap'],
      //'ingot_input': ['3x #forge:ingots/cobalt','#forge:ingots/netherite_scrap'],
    },
    {
      'material': 'nethersteel',
      'color': 0x403836,
      'type': 'alloy',
      'tier': 2,
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'plating'],
      'blockParts': ['storage_block'],
      'amount': 8,
      'dust_input': ['8x #forge:dusts/steel', '#forge:ingots/netherite_scrap'],
      'ingot_input': ['8x #forge:ingots/steel', '#forge:ingots/netherite_scrap'],
      'tinkers_input': [{name: 'tconstruct:molten_debris',amount: 90},{tag: 'forge:molten_steel',amount: 720}],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_nethersteel',
    },
    {
      'material': 'black_iron',
      'color': 0x403836,
      'type': 'alloy',
      'tier': 2,
      'itemParts': ['dust', 'plate', 'plating'],
      'blockParts': [],
      'amount': 2,
      'dust_input': ['2x #forge:dusts/iron', '#forge:dusts/graphite', '#forge:dusts/obsidian'],
      'ingot_input': ['2x #forge:ingots/iron', '#forge:ingots/graphite', '#forge:ingots/obsidian'],
      'tinkers_input': [{name: 'tconstruct:molten_iron',amount: 90},{name: 'kubejs:molten_carbon',amount: 100},{name: 'tconstruct:molten_obsidian',amount: 1000}],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_black_iron',
    },
    {
      'material': 'battery_alloy',
      'color': 0x537291,
      'type': 'alloy',
      'tier': 2,
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'plating'],
      'blockParts': ['storage_block'],
      'amount': 2,
      'dust_input': ['2x #forge:dusts/lead', '#forge:dusts/tin'],
      'ingot_input': ['2x #forge:ingots/lead', '#forge:ingots/tin'],
      'tinkers_input': [{tag: 'forge:molten_lead',amount: 180},{tag: 'forge:molten_tin',amount: 90}],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_battery_alloy',
    },
    
    {
      'material': 'illuminated_menril',
      'color': 0x2fc0f5,
      'type': 'alloy',
      'tier': 2,
      'itemParts': ['ingot', 'dust', 'nugget', 'plate', 'wire', 'plating'],
      'blockParts': ['storage_block'],
      'amount': 1,
      'dust_input': ['2x #forge:dusts/dielectric_alloy', '#forge:dusts/glowstone', 'integrateddynamics:crystalized_menril_chunk'],
      'ingot_input': ['2x #forge:ingots/dielectric_alloy', '#forge:dusts/glowstone', 'integrateddynamics:crystalized_menril_chunk'],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_illuminated_menril',
    },
    /////////////// Tier 3 Alloys: Arc Furnace or chapter 3 /////////////////////////////
    
    
    {
      'material': 'white_alloy',
      'color': 0xe9f1f5,
      'type': 'alloy',
      'tier': 3,
      'itemParts': ['ingot', 'dust', 'nugget', 'plate', 'rod', 'wire', 'model_spool', 'model_wire_coil'],
      'blockParts': ['storage_block', 'coil'],
      'amount': 3,
      'dust_input': ['2x #forge:dusts/silver', '#forge:dusts/magnesium', '#forge:dusts/quartz'],
      'ingot_input': ['2x #forge:ingots/silver', '#forge:ingots/magnesium', '#forge:gems/quartz'],
      'tinkers_input': [{tag: 'forge:molten_silver',amount: 180},{tag: 'forge:molten_magnesium',amount: 90},{tag: 'tconstruct:molten_quartz',amount: 100}],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_white_alloy',
    },
    {
      'material': 'compressed_steel',
      'color': 0x6b6b6b,
      'type': 'alloy',
      'tier': 3,
      'itemParts': ['dust', 'plate', 'rod', 'component', 'sheet'],
      'blockParts': ['sheetmetal'],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_compressed_steel',
    },
    {
      'material': 'pressurized_aluminum_alloy',
      'color': 0xc8e0e0,
      'type': 'alloy',
      'tier': 3,
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'gear', 'rod', 'plating'],
      'blockParts': ['storage_block'],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_pressurized_aluminum_alloy',
    },
    {
      'material': 'netherite',
      'color': 0x524c49,
      'type': 'alloy',
      'tier': 3,
      'itemParts': [],
      'blockParts': [],
      'amount': 1,
      'dust_input': ['4x #forge:ingots/netherite_scrap','4x #forge:dusts/gold'],
      'ingot_input': ['4x #forge:ingots/netherite_scrap','4x #forge:ingots/gold'],
    },
    {
      'material': 'industrial_alloy',
      'color': 0x574735,
      'type': 'alloy',
      'tier': 3,
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'gear', 'rod', 'plating', 'component'],
      'blockParts': ['storage_block'],
      //'amount': 8,
      //'dust_input': ['1x #forge:ingots/netherite_scrap','4x #forge:dusts/steel'],
      //'ingot_input': ['1x #forge:ingots/netherite_scrap','4x #forge:ingots/steel'],
    },
    {
      'material': 'fluix_steel',
      'color': 0x7e5fb0,
      'type': 'alloy',
      'tier': 2,
      'itemParts': ['dust', 'plate', 'gear', 'rod', 'wire'],
      'blockParts': ['storage_block','scaffolding'],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_fluix_steel',
      'amount': 1,
      'dust_input': ['#forge:dusts/steel', '2x lazierae2:carbonic_fluix_dust'],
      'ingot_input': ['#forge:ingots/steel', '2x lazierae2:carbonic_fluix_dust'],
      'tinkers_input': [{tag: 'forge:molten_steel',amount: 90},{name: 'kubejs:molten_fluix',amount: 400},{name: 'kubejs:molten_carbon',amount: 400},{tag: 'tconstruct:molten_quartz',amount: 200}],
    },
    {
      'material': 'lumium',
      'color': 0xffd894,
      'type': 'alloy',
      'tier': 3,
      'itemParts': ['rod', 'base_ingot', 'base_dust', 'plating'],
      'blockParts': [],
      'type': 'alloy',
      'fluid_id': 'tconstruct:molten_lumium',
      'amount': 4,
      'base': true,
      'dust_input': ['3x #forge:dusts/aluminum','2x #forge:dusts/white_alloy','8x create:experience_nugget'],
      'ingot_input': ['3x #forge:ingots/aluminum','2x #forge:ingots/white_alloy','8x create:experience_nugget'],
      'fluid_input': 'thermal:glowstone',
      'fluid_amount': 250,
    },

    {
      'material': 'arcane_gold',
      'color': 0xe8a02a,
      'type': 'alloy',
      'tier': 3,
      'itemParts': ['plate', 'gear', 'rod', 'dust'], 
      'blockParts': [],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_arcane_gold',
      'amount': 1,
      'dust_input': ['#forge:dusts/auric_gold', '#forge:gems/luminite', '2x #forge:dusts/arcane_crystal', '2x #forge:dusts/mundabitur'],
    },
    {
      'material': 'manyullyn',
      'color': 0x8b68ad,
      'type': 'alloy',
      'tier': 3,
      'itemParts': ['dust', 'plate', 'gear', 'rod'],
      'blockParts': [],
      'fluid_id': 'tconstruct:molten_manyullyn',
      'amount': 4,
      'dust_input': ['3x #forge:dusts/cobalt','#forge:ingots/netherite_scrap'],
      'ingot_input': ['3x #forge:ingots/cobalt','#forge:ingots/netherite_scrap'],
    },


    {
      'material': 'soulsteel',
      'color': 0x5c544d,
      'type': 'alloy',
      'tier': 3,
      'itemParts': ['plate', 'rod', 'gear'],
      'blockParts': [],
      //'amount': 3,
      //'dust_input': ['2x #forge:dusts/manyullyn', '#forge:dusts/titanium', '#forge:gems/uraninite'],
      //'ingot_input': ['2x #forge:ingots/manyullyn', '#forge:ingots/titanium', '#forge:gems/uraninite'],
      'fluid_id': 'tconstruct:molten_soulsteel',
    },

    {
      'material': 'titanite',
      'color': 0x9754d1,
      'type': 'alloy',
      'tier': 3,
      'itemParts': ['ingot', 'dust', 'nugget', 'plate', 'rod', 'gear', 'interlocking_component', 'wire', 'plating', 'bolt', 'hull_panel'],
      'blockParts': ['storage_block', 'scaffolding', 'hull_casing', 'frame_box'],
      'amount': 3,
      'dust_input': ['2x #forge:dusts/manyullyn', '#forge:dusts/titanium', '#forge:gems/uraninite'],
      'ingot_input': ['2x #forge:ingots/manyullyn', '#forge:ingots/titanium', '#forge:gems/uraninite'],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_titanite',
    },

    {
      'material': 'crystalized_alloy',
      'color': 0x12fff7,
      'type': 'alloy',
      'tier': 3,
      'itemParts': ['ingot', 'dust', 'nugget', 'plate', 'wire', 'plating'],
      'blockParts': ['storage_block'],
      'amount': 1,
      //'dust_input': ['2x #forge:dusts/illuminated_menril', '#forge:dusts/glowstone', 'integrateddynamics:crystalized_menril_chunk'],
      //'ingot_input': ['2x #forge:ingots/illuminated_menril', '#forge:dusts/glowstone', 'integrateddynamics:crystalized_menril_chunk'],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_crystalized_alloy',
    },

    
    /////////////// Tier 4 Alloys Mixer Only or chapter 4 /////////////////////////////custom

    {
      'material': 'aerospace_alloy',
      'color': 0xe3feff,
      'type': 'alloy',
      'tier': 4,
      'itemParts': ['ingot', 'nugget', 'dust',  'plate', 'gear', 'rod', 'plating', 'model_rocket_nose_cone', 'rocket_fin', 'sheet'],
      'blockParts': ['storage_block'],
      'fluid_id': 'kubejs:molten_aerospace_alloy',
      'fluid': 'thick',
      'amount': 5,
      'dust_input': ['3x #forge:dusts/pressurized_aluminum_alloy','#forge:dusts/titanium','#forge:dusts/chromium','#forge:dusts/tier_2_mechanical_alloy'],
      'ingot_input': ['3x #forge:ingots/pressurized_aluminum_alloy','#forge:ingots/titanium','#forge:ingots/chromium','#forge:ingots/tier_2_mechanical_alloy'],
    },
    {
      'material': 'chemically_inert_alloy',
      'color': 0xa5afb0,
      'type': 'alloy',
      'tier': 4,
      'itemParts': ['ingot', 'nugget', 'dust',  'plate', 'gear', 'rod', 'plating'],
      'blockParts': ['storage_block'],
      'fluid_id': 'kubejs:molten_chemically_inert_alloy',
      'fluid': 'thick',
      'amount': 3,
      'dust_input': ['3x #forge:dusts/osmium','#forge:dusts/white_alloy','pneumaticcraft:plastic'],
      'ingot_input': ['3x #forge:ingots/osmium','#forge:ingots/white_alloy','pneumaticcraft:plastic'],
    },
    {
      'material': 'lunar_alloy',
      'color': 0xebb250,
      'type': 'alloy',
      'tier': 4,
      'itemParts': ['ingot', 'nugget', 'dust',  'plate', 'plating', 'wire', 'model_spool'],
      'blockParts': ['storage_block'],
      'amount': 3,
      'dust_input': ['2x #forge:dusts/desh','2x beyond_earth:cheese','4x beyond_earth:moon_stone'],
      'ingot_input': ['2x #forge:ingots/desh','2x beyond_earth:cheese','4x beyond_earth:moon_stone'],
    },
    {
      'material': 'damascus_steel',
      'color': 0x828282,
      'type': 'alloy',
      'tier': 4,
      'itemParts': ['custom_ingot', 'nugget', 'plate', 'gear', 'rod'],
      'blockParts': ['storage_block'],
      'fluid_id': 'kubejs:molten_damascus_steel',
      'fluid': 'thick',
    },
    //{
    //  'material': 'bendalloy',
    //  'color': 0xbab6a2,
    //  'type': 'alloy',
    //  'tier': 4,
    //  'itemParts': [ 'plate', 'gear', 'dust', 'rod'],
    //  'blockParts': [],
    //  'fluid': 'thick',
    //  'fluid_id': 'kubejs:molten_bendalloy',
    //  'amount': 3,
    //  'dust_input': ['2x #forge:dusts/cadmium','#forge:dusts/lead'],
    //  'ingot_input': ['2x #forge:ingots/cadmium','#forge:ingots/lead'],
    //  'tinkers_input': [{tag: 'forge:molten_cadmium',amount: 180},{tag: 'forge:molten_lead',amount: 90}],
    //  'allomancy': 'Bendalloy speeds up everything in a bubble around you. Furnaces, crops, and mobs all go faster!',
    //  'feruchemy': 'Nutrition--Gives Saturation(Restores hunger bar) or Drains hunger bar.'
    //},
    //{
    //  'material': 'nicrosil',
    //  'color': 0xa9a9b0,
    //  'type': 'alloy',
    //  'tier': 4,
    //  'itemParts': [ 'plate', 'gear', 'dust', 'rod'],
    //  'blockParts': [],
    //  'fluid': 'thick',
    //  'fluid_id': 'kubejs:molten_nicrosil',
    //  'amount': 4,
    //  'dust_input': ['3x #forge:dusts/chromium','#forge:dusts/iron'],
    //  'ingot_input': ['3x #forge:ingots/chromium','#forge:ingots/iron'],
    //  'tinkers_input': [{tag: 'forge:molten_chromium',amount: 270},{tag: 'forge:molten_iron',amount: 90}],
    //  'allomancy': 'Nicrosil enhances whatever metal the player you left click on is burning. When you stop enhancing them, they will lose their stock of the currently burning metal.',
    //  'feruchemy': 'Pure Power--If you Store here first, any charges gained by Storing other metals gets stored here, albeit at a reduced rate. But if you Tap here first, charges will be consumed here before they are consumed by other metals.'
    //},
    {
      'material': 'signalum',
      'color': 0xff6e4a,
      'tier': 4,
      'itemParts': ['rod', 'base_ingot', 'base_dust', 'plating'],
      'blockParts': ['scaffolding'],
      'type': 'alloy',
      'fluid_id': 'tconstruct:molten_signalum',
      'amount': 4,
      'base': true,
      'dust_input': ['2x #forge:dusts/lumium', '3x #forge:dusts/titanium','2x #forge:dusts/energetic_alloy','4x hostilenetworks:nether_prediction'],
      'ingot_input': ['2x #forge:ingots/lumium', '3x #forge:ingots/titanium','2x #forge:ingots/energetic_alloy','4x hostilenetworks:nether_prediction'],
      'fluid_input': 'thermal:redstone',
      'fluid_amount': 250,
    },
    
    /////////////// Tier 5 Alloys /////////////////////////////
    {
      'material': 'fireite',
      'color': 0x4a1304,
      'tier': 5,
      'itemParts': ['dust', 'plate', 'gear', 'rod'],
      'blockParts': [],
      'type': 'alloy',
    },
    {
      'material': 'stainless_steel',
      'color': 0xcedadb,
      'type': 'alloy',
      'tier': 5,
      'itemParts': ['ingot', 'nugget', 'dust',  'plate', 'gear', 'rod', 'plating'],
      'blockParts': ['storage_block', 'scaffolding'],
      'fluid_id': 'kubejs:molten_stainless_steel',
      'fluid': 'thick',
      'amount': 9, 
      'dust_input': ['4x #forge:dusts/steel','3x #forge:dusts/invar','#forge:dusts/chromium','#forge:dusts/manganese'],
      'ingot_input': ['4x #forge:ingots/steel','3x #forge:ingots/invar','#forge:ingots/chromium', '#forge:ingots/manganese'],
    },
    {
      'material': 'inconel',
      'color': 0x484e5e,
      'type': 'alloy',
      'tier': 5,
      'itemParts': ['ingot', 'nugget', 'dust',  'plate', 'gear', 'rod', 'plating', 'hull_panel'],
      'blockParts': ['storage_block'],
      'fluid_id': 'kubejs:molten_inconel',
      'fluid': 'thick',
      'amount': 7,
      'dust_input': ['3x #forge:dusts/nickel','2x #forge:dusts/cobalt','#forge:dusts/chromium','#forge:dusts/molybdenum'],
      'ingot_input': ['3x #forge:ingots/nickel','2x #forge:ingots/cobalt','#forge:ingots/chromium', '#forge:ingots/molybdenum'],
    },
    {
      'material': 'promethium',
      'color': 0x541f11,
      'type': 'alloy',
      'tier': 5,
      'itemParts': ['ingot', 'nugget', 'dust',  'plate', 'gear', 'rod', 'plating'],
      'blockParts': ['storage_block'],
      'fluid_id': 'kubejs:molten_promethium',
      'fluid': 'thick',
      'amount': 4,
      'dust_input': ['4x #forge:dusts/titanium','#forge:dusts/fireite','#forge:dusts/molybdenum','4x kubejs:pyrotheum_dust'],
      'ingot_input': ['4x #forge:ingots/titanium','#forge:ingots/fireite', '#forge:ingots/molybdenum','4x kubejs:pyrotheum_dust'],
    },

    {
      'material': 'exoskeleton_composit',
      'color': 0x9c845a,
      'type': 'alloy',
      'tier': 5,
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'plating', 'reinforced_plating', 'hull_panel', 'base_ingot', 'base_dust'],
      'blockParts': ['storage_block'],
      'fluid_id': 'kubejs:molten_exoskeleton_composit',
      'fluid': 'thick',
      //'amount': 3,
      //'dust_input': ['3x #forge:dusts/adamantine_alloy','#forge:dusts/promethium','chemlib:chitin_dust'],
      //'ingot_input': ['3x #forge:ingots/adamantine_alloy','#forge:ingots/promethium', 'chemlib:chitin_dust'],
    },
    {
      'material': 'advanced_battery_alloy',
      'color': 0x6aa1d4,
      'type': 'alloy',
      'tier': 5,
      'itemParts': ['ingot', 'nugget', 'dust',  'plate', 'plating'],
      'blockParts': ['storage_block'],
      'amount': 3,
      'dust_input': ['2x #forge:dusts/battery_alloy', '2x #forge:dusts/platinum', '#forge:dusts/cadmium'],
      'ingot_input': ['2x #forge:ingots/battery_alloy', '2x #forge:ingots/platinum','#forge:ingots/cadmium'],
    },
    {
      'material': 'enderium',
      'color': 0x5fc4d4,
      'tier': 5,
      'itemParts': ['rod', 'plating', 'hull_panel', 'base_ingot', 'base_dust'],
      'blockParts': [],
      'type': 'alloy',
      'fluid_id': 'tconstruct:molten_enderium',
      'amount': 4,
      'base': true,
      'dust_input': ['2x #forge:dusts/signalum', '3x #forge:dusts/rune', '#forge:dusts/molybdenum', '4x hostilenetworks:end_prediction'],
      'ingot_input': ['2x #forge:ingots/signalum', '3x #forge:ingots/rune', '#forge:ingots/molybdenum', '4x hostilenetworks:end_prediction'],
      'fluid_input': 'thermal:ender',
      'fluid_amount': 250,
    },

    /////////////// Tier 6 Alloys /////////////////////////////
    {
      'material': 'adamantine_alloy',
      'color': 0xd1193b,
      'type': 'alloy',
      'tier': 6,
      'itemParts': ['ingot', 'nugget', 'dust',  'plate', 'gear', 'rod', 'plating', 'reinforced_plating', 'model_rocket_nose_cone', 'rocket_fin'],
      'blockParts': ['storage_block'],
      'fluid_id': 'kubejs:molten_adamantine_alloy',
      'fluid': 'thick',
      'amount': 3,
      'dust_input': ['3x #forge:dusts/adamantium','#forge:dusts/energetic_alloy','#forge:dusts/manasteel'],
      'ingot_input': ['3x #forge:ingots/adamantium','#forge:ingots/energetic_alloy', '#forge:ingots/manasteel'],
    },
    /////////////// Ore /////////////////////////////
    /*
    {
      'material': 'rutile',
      'color': 0xff4d4d,
      'type': 'base_metal',
      'itemParts': ['dust'],
      'blockParts': [],
      'ore': true
    },
    {
      'material': 'sphalerite',
      'color': 0x7b7db0,
      'type': 'base_metal',
      'itemParts': ['dust'],
      'blockParts': [],
      'ore': true
    },*/
    ///////////////////////// Thermogenic //////////////////////////////////////
    {
      'material': 'imortite',
      'color': 0xf28a2e,
      'tier': 1,
      'type': 'compound_ore',
      'itemParts': ['dust', 'ingot'],
      'blockParts': [],
      'fluid': 'thick',
      'ore': true,
      'raw_ore': true,
      'components': ['copper','zinc', 'nickel', 'uranium', 'platinum', 'orichalcum', 'adamantium', 'vibranium', 'draconium'],
      'gem_components': ['sulfur', 'fluorite'],
      'byproducts': ['imortite', 'potentium'],
    },
    {
      'material': 'potentium',
      'color': 0xba49e3,
      'tier': 1,
      'type': 'compound_ore',
      'itemParts': ['dust', 'ingot'],
      'blockParts': [],
      'fluid': 'thick',
      'ore': true,
      'raw_ore': true,
      'components': ['gold','zinc', 'mithril', 'aetherium', 'desh', 'cadmium', 'calorite', 'vibranium', 'draconium'],
      'gem_components': ['diamond', 'amethyst'],
      'byproducts': ['potentium', 'kharaxium'],
    },
    {
      'material': 'kharaxium',
      'color': 0x8f0000,
      'tier': 1,
      'type': 'compound_ore',
      'itemParts': ['dust', 'ingot'],
      'blockParts': [],
      'fluid': 'thick',
      'ore': true,
      'raw_ore': true,
      'components': ['iron','arcanite', 'aluminum', 'magnesium', 'rune', 'ostrum', 'adamantium', 'vibranium', 'draconium'],
      'gem_components': ['ruby', 'cinnabar'],
      'byproducts': ['kharaxium', 'imortite'],
    },

    {
      'material': 'thermogenic',
      'color': 0xf06330,
      'tier': 3,
      'type': 'compound_rare_metal',
      'itemParts': ['dust', 'shard'],
      'blockParts': [],
      'fluid': 'thick',
      'components': ['uranium', 'chromium', 'magnesium', 'oxygen'],
      'amount': 1,
      'dust_input': ['#forge:ores/chunk/kharaxium','#forge:ores/chunk/potentium','#forge:ores/chunk/imortite'],
      'ore': true
    },
//////////////////////// Thermolytic /////////////////////////
    {
      'material': 'vincyte',
      'color': 0x0046d1,
      'tier': 1,
      'type': 'compound_ore',
      'itemParts': ['dust', 'ingot'],
      'blockParts': [],
      'fluid': 'thick',
      'ore': true,
      'raw_ore': true,
      'components': ['copper', 'arcanite', 'cobalt', 'titanium', 'platinum', 'tungsten', 'iridium', 'uru', 'draconium'],
      'gem_components': ['lapis', 'apatite'],
      'byproducts': ['vincyte', 'densite'],
    },
    {
      'material': 'densite',
      'color': 0x667e94,
      'tier': 1,
      'type': 'compound_ore',
      'itemParts': ['dust', 'ingot'],
      'blockParts': [],
      'fluid': 'thick',
      'ore': true,
      'raw_ore': true,
      'components': ['tin', 'silver', 'aluminum', 'magnesium', 'osmium', 'ostrum', 'iridium', 'uru', 'draconium'],
      'gem_components': ['quartz', 'certus_quartz'],
      'byproducts': ['densite', 'jimmium'],
    },
    {
      'material': 'jimmium',
      'color': 0x270059,
      'tier': 1,
      'type': 'compound_ore',
      'itemParts': ['dust', 'ingot'],
      'blockParts': [],
      'fluid': 'thick',
      'ore': true,
      'raw_ore': true,
      'components': ['iron', 'lead', 'nickel', 'titanium', 'osmium', 'tungsten', 'calorite', 'uru', 'draconium'],
      'gem_components': ['emerald', 'niter'],
      'byproducts': ['jimmium', 'vincyte'],
    },
    {
      'material': 'thermolytic',
      'color': 0x42f5da,
      'tier': 3,
      'type': 'compound_rare_metal',
      'itemParts': ['dust', 'shard'],
      'blockParts': [],
      'fluid': 'thick',
      'components': ['titanium', 'manganese', 'thorium', 'hydrogen'],
      'amount': 1,
      'dust_input': ['#forge:ores/chunk/jimmium','#forge:ores/chunk/densite','#forge:ores/chunk/vincyte'],
      'ore': true
    },
    
    
    /////////////// CUSTOM ALLOYS /////////////////////////////

    ////////// MECHANICAL ///////////
    {
      'material': 'tier_1_mechanical_alloy',
      'color': 0x74d5f2,
      'type': 'alloy',
      'tier': 1,
      'iconset': 'mechanical',
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'gear', 'interlocking_component', 'rod', 'model_robot_arm', 'wire'],
      'blockParts': ['storage_block', 'cog_block',],
      'fluid_id': 'kubejs:molten_tier_1_mechanical_alloy',
      'fluid': 'thick',
      'amount': 2,
      'dust_input': ['3x #forge:dusts/tin','#forge:dusts/zinc',['ars_nouveau:air_essence','elementalcraft:powerful_air_shard']],
      'ingot_input': ['3x #forge:ingots/tin', '#forge:ingots/zinc',['ars_nouveau:air_essence','elementalcraft:powerful_air_shard']],  
    },
    {
      'material': 'tier_2_mechanical_alloy',
      'color': 0x399adb,
      'type': 'alloy',
      'tier': 3,
      'iconset': 'mechanical',
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'gear', 'interlocking_component', 'rod', 'model_robot_arm', 'wire'],
      'blockParts': ['storage_block', 'cog_block',],
      'fluid_id': 'kubejs:molten_tier_2_mechanical_alloy',
      'fluid': 'thick',
      'amount': 2,
      'dust_input': ['3x #forge:dusts/tier_1_mechanical_alloy','2x #forge:dusts/aluminum','#forge:dusts/magnesium'],
      'ingot_input': ['3x #forge:ingots/tier_1_mechanical_alloy','2x #forge:ingots/aluminum', '#forge:ingots/magnesium'],
    },
    {
      'material': 'tier_3_mechanical_alloy',
      'color': 0x2785e3,
      'type': 'alloy',
      'tier': 5,
      'iconset': 'mechanical',
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'gear', 'interlocking_component', 'rod', 'model_robot_arm', 'wire'],
      'blockParts': ['storage_block', 'cog_block',],
      'fluid_id': 'kubejs:molten_tier_3_mechanical_alloy',
      'fluid': 'thick',
      'amount': 1,
      'dust_input': ['3x #forge:dusts/tier_2_mechanical_alloy','2x #forge:dusts/platinum','#forge:dusts/ostrum','create:precision_mechanism'],
      'ingot_input': ['3x #forge:ingots/tier_2_mechanical_alloy','2x #forge:ingots/platinum', '#forge:ingots/ostrum','create:precision_mechanism'],
    },
    {
      'material': 'tier_4_mechanical_alloy',
      'color': 0x055ce8,
      'type': 'alloy',
      'tier': 7,
      'iconset': 'mechanical',
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'gear', 'interlocking_component', 'rod', 'model_robot_arm', 'wire'],
      'blockParts': ['storage_block', 'cog_block',],
      'fluid_id': 'kubejs:molten_tier_4_mechanical_alloy',
      'fluid': 'thick',
      'amount': 1,
      'dust_input': ['3x #forge:dusts/tier_3_mechanical_alloy','2x #forge:dusts/iridium','#forge:dusts/vibranium','create:precision_mechanism'],
      'ingot_input': ['3x #forge:ingots/tier_3_mechanical_alloy','2x #forge:ingots/iridium', '#forge:ingots/vibranium','create:precision_mechanism'],
    },
    ////////// ELECTRICAL ///////////
    {
      'material': 'tier_1_electrical_alloy',
      'color': 0xf0963c,
      'type': 'alloy',
      'tier': 1,
      'iconset': 'electrical',
      'itemParts': ['ingot', 'nugget', 'dust',  'plate', 'wire', 'model_spool', 'model_wire_coil', 'sheet', 'model_dual_coil', 'model_part_bundle'],
      'blockParts': ['storage_block', 'coil'],
      'fluid_id': 'kubejs:molten_tier_1_electrical_alloy',
      'fluid': 'thick',
      'amount': 2,
      'dust_input': ['3x #forge:dusts/copper', '#forge:dusts/silver', ['ars_nouveau:fire_essence','elementalcraft:powerful_fire_shard']],
      'ingot_input': ['3x #forge:ingots/copper','#forge:ingots/silver', ['ars_nouveau:fire_essence','elementalcraft:powerful_fire_shard']],
    },
    {
      'material': 'tier_2_electrical_alloy',
      'color': 0xf58836,
      'type': 'alloy',
      'tier': 3,
      'iconset': 'electrical',
      'itemParts': ['ingot', 'nugget', 'dust',  'plate', 'wire', 'model_spool', 'model_wire_coil', 'sheet', 'model_dual_coil', 'model_part_bundle'],
      'blockParts': ['storage_block', 'coil'],
      'fluid_id': 'kubejs:molten_tier_2_electrical_alloy',
      'fluid': 'thick',
      'amount': 2,
      'dust_input': ['3x #forge:dusts/tier_1_electrical_alloy', '2x #forge:dusts/amethyst_bronze', '#forge:dusts/uranium'],
      'ingot_input': ['3x #forge:ingots/tier_1_electrical_alloy', '2x #forge:ingots/amethyst_bronze', '#forge:ingots/uranium'],
    },
    {
      'material': 'tier_3_electrical_alloy',
      'color': 0xe6501e,
      'type': 'alloy',
      'tier': 5,
      'iconset': 'electrical',
      'itemParts': ['ingot', 'nugget', 'dust',  'plate', 'wire', 'model_spool', 'model_wire_coil', 'sheet', 'model_dual_coil', 'model_part_bundle'],
      'blockParts': ['storage_block', 'coil'],
      'fluid_id': 'kubejs:molten_tier_3_electrical_alloy',
      'fluid': 'thick',
      'amount': 1,
      'dust_input': ['3x #forge:dusts/tier_2_electrical_alloy', '2x #forge:dusts/osmium', '#forge:dusts/promethium', 'immersiveengineering:component_electronic'],
      'ingot_input': ['3x #forge:ingots/tier_2_electrical_alloy', '2x #forge:ingots/osmium', '#forge:ingots/promethium', 'immersiveengineering:component_electronic'],
    },
    {
      'material': 'tier_4_electrical_alloy',
      'color': 0xf55014,
      'type': 'alloy',
      'tier': 7,
      'iconset': 'electrical',
      'itemParts': ['ingot', 'nugget', 'dust',  'plate', 'wire', 'model_spool', 'model_wire_coil', 'sheet', 'model_dual_coil', 'model_part_bundle'],
      'blockParts': ['storage_block', 'coil'],
      'fluid_id': 'kubejs:molten_tier_4_electrical_alloy',
      'fluid': 'thick',
      'amount': 1,
      'dust_input': ['3x #forge:dusts/tier_3_electrical_alloy', '2x #forge:dusts/palladium', '#forge:dusts/uru', 'kubejs:energy_orb_full'],
      'ingot_input': ['3x #forge:ingots/tier_3_electrical_alloy', '2x #forge:ingots/palladium', '#forge:ingots/uru', 'kubejs:energy_orb_full'],
    },
    ////////// MAGICAL ///////////
    {
      'material': 'tier_1_magical_alloy',
      'color': 0x9383c7,
      'type': 'alloy',
      'tier': 1,
      'iconset': 'magical',
      'itemParts': ['ingot', 'nugget', 'dust', 'rod', 'ring', 'sprocket', 'plate'],
      'blockParts': ['storage_block'],
      'fluid_id': 'kubejs:molten_tier_1_magical_alloy',
      'fluid': 'thick',
      'amount': 2,
      'dust_input': ['3x #forge:dusts/gold', '#forge:dusts/drenched_arcanite',['ars_nouveau:water_essence','elementalcraft:powerful_water_shard']],
      'ingot_input': ['3x #forge:ingots/gold', '#forge:ingots/drenched_arcanite',['ars_nouveau:water_essence','elementalcraft:powerful_water_shard']],
    },
    {
      'material': 'tier_2_magical_alloy',
      'color': 0x7e47d6,
      'type': 'alloy',
      'tier': 3,
      'iconset': 'magical',
      'itemParts': ['ingot', 'nugget', 'dust', 'rod', 'ring', 'sprocket', 'plate'],
      'blockParts': ['storage_block'],
      'fluid_id': 'kubejs:molten_tier_2_magical_alloy',
      'fluid': 'thick',
      'amount': 2,
      'dust_input': ['3x #forge:dusts/tier_1_magical_alloy', '2x #forge:dusts/infused_mithril', '#forge:dusts/manyullyn'],
      'ingot_input': ['3x #forge:ingots/tier_1_magical_alloy', '2x #forge:ingots/infused_mithril', '#forge:ingots/manyullyn'],
    },
    {
      'material': 'tier_3_magical_alloy',
      'color': 0x815cd6,
      'type': 'alloy',
      'tier': 5,
      'iconset': 'magical',
      'itemParts': ['ingot', 'nugget', 'dust', 'rod', 'ring', 'sprocket', 'plate'],
      'blockParts': ['storage_block'],
      'fluid_id': 'kubejs:molten_tier_3_magical_alloy',
      'fluid': 'thick',
      'amount': 1,
      'dust_input': ['3x #forge:dusts/tier_2_magical_alloy', '2x #forge:dusts/manasteel', '#forge:dusts/orichalcum'],
      'ingot_input': ['3x #forge:ingots/tier_2_magical_alloy', '2x #forge:ingots/manasteel', '#forge:ingots/orichalcum'],
    },
    {
      'material': 'tier_4_magical_alloy',
      'color': 0x7b28e0,
      'type': 'alloy',
      'tier': 7,
      'iconset': 'magical',
      'itemParts': ['ingot', 'nugget', 'dust', 'rod', 'ring', 'sprocket', 'plate'],
      'blockParts': ['storage_block'],
      'fluid_id': 'kubejs:molten_tier_4_magical_alloy',
      'fluid': 'thick',
      'amount': 1,
      'dust_input': ['3x #forge:dusts/tier_3_magical_alloy', '2x #forge:dusts/terrasteel', '#forge:dusts/draconium'],
      'ingot_input': ['3x #forge:ingots/tier_3_magical_alloy', '2x #forge:ingots/terrasteel', '#forge:ingots/draconium'],
    },
    ////////// STRUCTURAL ///////////
    {
      'material': 'tier_1_structural_alloy',
      'color': 0x76b090,
      'type': 'alloy',
      'tier': 1,
      'iconset': 'structural',
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'rod', 'plating', 'reinforced_plating', 'hull_panel', 'bolt', 'sheet', 'component'],
      'blockParts': ['storage_block', 'casing', 'scaffolding', 'hull_casing', 'frame_box', 'sheetmetal'],
      'fluid_id': 'kubejs:molten_tier_1_structural_alloy',
      'fluid': 'thick',
      'amount': 2,
      'dust_input': ['3x #forge:dusts/iron', '#forge:dusts/lead',['ars_nouveau:earth_essence','elementalcraft:powerful_earth_shard']],
      'ingot_input': ['3x #forge:ingots/iron', '#forge:ingots/lead',['ars_nouveau:earth_essence','elementalcraft:powerful_earth_shard']],
    },
    {
      'material': 'tier_2_structural_alloy',
      'color': 0x11b861,
      'type': 'alloy',
      'tier': 3,
      'iconset': 'structural',
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'rod', 'plating', 'reinforced_plating', 'hull_panel', 'bolt', 'sheet', 'component'],
      'blockParts': ['storage_block', 'casing', 'scaffolding', 'hull_casing', 'frame_box', 'sheetmetal'],
      'fluid_id': 'kubejs:molten_tier_2_structural_alloy',
      'fluid': 'thick',
      'amount': 2,
      'dust_input': ['3x #forge:dusts/tier_1_structural_alloy','2x #forge:dusts/cobalt_brass','#forge:dusts/titanium'],
      'ingot_input': ['3x #forge:ingots/tier_1_structural_alloy','2x #forge:ingots/cobalt_brass', '#forge:ingots/titanium'],
    },
    {
      'material': 'tier_3_structural_alloy',
      'color': 0x039c17,
      'type': 'alloy',
      'tier': 5,
      'iconset': 'structural',
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'rod', 'plating', 'reinforced_plating', 'hull_panel', 'bolt', 'sheet', 'component'],
      'blockParts': ['storage_block', 'casing', 'scaffolding', 'hull_casing', 'frame_box', 'sheetmetal'],
      'fluid_id': 'kubejs:molten_tier_3_structural_alloy',
      'fluid': 'thick',
      'amount': 1,
      'dust_input': ['3x #forge:dusts/tier_2_structural_alloy','2x #forge:dusts/desh','#forge:dusts/tungsten', 'create:railway_casing'],
      'ingot_input': ['3x #forge:ingots/tier_2_structural_alloy','2x #forge:ingots/desh', '#forge:ingots/tungsten', 'create:railway_casing'],
    },
    {
      'material': 'tier_4_structural_alloy',
      'color': 0x096315,
      'type': 'alloy',
      'tier': 7,
      'iconset': 'structural',
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'rod', 'plating', 'reinforced_plating', 'hull_panel', 'bolt', 'sheet', 'component'],
      'blockParts': ['storage_block', 'casing', 'scaffolding', 'hull_casing', 'frame_box', 'sheetmetal'],
      'fluid_id': 'kubejs:molten_tier_4_structural_alloy',
      'fluid': 'thick',
      'amount': 1,
      'dust_input': ['3x #forge:dusts/tier_3_structural_alloy','2x #forge:dusts/adamantium','#forge:dusts/vibraniumm', 'mekanism:hdpe_sheet'],
      'ingot_input': ['3x #forge:ingots/tier_3_structural_alloy','2x #forge:ingots/adamantium', '#forge:ingots/vibraniumm', 'mekanism:hdpe_sheet'],
    },



    /////////////// Other /////////////////////////////
    {
      'material': 'slag',
      'color': 0x947b6c,
      'itemParts': ['dust'],
      'blockParts': [],
      'fluid': 'thick'
    },
    {
      'material': 'crystal_slag',
      'color': 0xb1d15a,
      'type': 'gem',
      'itemParts': ['gem', 'dust'],
      'blockParts': [],
      'fluid': 'thick'
    },
    {
      'material': 'rich_slag',
      'color': 0x8a472d,
      'itemParts': ['dust'],
      'blockParts': [],
      'fluid': 'thick'
    },
    {
      'material': 'end_stone',
      'color': 0xebe596,
      'type': 'stone',
      'itemParts': ['dust'],
      'blockParts': [],
      'fluid': 'thick'
    },
    //{
    //  'material': 'netherrack',
    //  'color': 0x611324,
    //  'type': 'stone',
    //  'itemParts': ['dust'],
    //  'blockParts': [],
    //  'fluid': 'thick'
    //},
    {
      'material': 'wood',
      'color': 0x825c45,
      'itemParts': [],
      'blockParts': ['scaffolding']
    },
    {
      'material': 'ancient_wood',
      'color': 0xa86cba,
      'itemParts': [],
      'blockParts': ['scaffolding']
    },
    {
      'material': 'redstone',
      'color': 0xf54242,
      'type': 'dust',
      'tier': 1,
      'itemParts': [],
      'blockParts': [],
      'ore': true
    },
    {
      'material': 'mana_diamond',
      'color': 0x3bfff8,
      'type': 'gem',
      'tier': 1,
      'itemParts': ['dust'],
      'blockParts': [],
    },
    {
      'material': 'sulfur',
      'color': 0xe1eb34,
      'type': 'gem',
      'iconset': 'sulfur',
      'itemParts': [],
      'blockParts': [],
      'ore': true
    },
    {
      'material': 'luminite',
      'color': 0xffed7a,
      'type': 'gem',
      'iconset': 'sapphire',
      'itemParts': ['gem', 'dust'],
      'blockParts': ['storage_block'],
      'ore': true,
      'burnTime': 16, //items * 200
      'fluid': 'thick'
    },
    {
      'material': 'manasteel',
      'color': 0x69a7ff,
      'type': 'magic_alloy',
      'tier': 4,
      'itemParts': ['dust', 'plate', 'gear', 'rod'],
      'blockParts': [],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_manasteel',
    },
    {
      'material': 'terrasteel',
      'tier': 5,
      'color': 0x63e645,
      'type': 'magic_alloy',
      'itemParts': ['plate', 'gear', 'rod', 'dust'],
      'blockParts': [],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_terrasteel',
    },
    {
      'material': 'elementium',
      'tier': 6,
      'color': 0xf569b6,
      'type': 'magic_alloy',
      'itemParts': ['plate',  'gear', 'rod'],
      'blockParts': [],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_elementium',
    },/*
    {
      'material': 'transmuted_silver',
      'color': 0xa9d0d9,
      'type': 'magic_alloy',
      'itemParts': ['plate', 'gear', 'rod'],
      'blockParts': []
    },*/
    {
      'material': 'infused_mithril',
      'tier': 3,
      'color': 0x54b33b,
      'type': 'magic_alloy',
      'itemParts': ['plate', 'gear', 'rod', 'dust', 'bolt'],
      'blockParts': [],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_infused_mithril',
    },
    {
      'material': 'tainted_gold',
      'tier': 3,
      'color': 0xa66032,
      'type': 'magic_alloy',
      'itemParts': ['plate', 'gear', 'rod', 'dust', 'bolt'],
      'blockParts': [],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_tainted_gold'
    },
    {
      'material': 'sky_metal',
      'tier': 4,
      'color': 0x83d5de,
      'type': 'magic_alloy',
      'itemParts': ['plate', 'gear', 'rod', 'dust', 'bolt'],
      'blockParts': ['storage_block'],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_sky_metal'
    },
    {
      'material': 'air',
      'color': 0xfcffbf,
      'type': 'element',
      'itemParts': [],
      'blockParts': [],
      'ore': true
    },
    {
      'material': 'earth',
      'color': 0x579c4e,
      'type': 'element',
      'itemParts': [],
      'blockParts': [],
      'ore': true
    },
    {
      'material': 'fire',
      'color': 0xe34536,
      'type': 'element',
      'itemParts': [],
      'blockParts': [],
      'ore': true
    },
    {
      'material': 'water',
      'color': 0x4272f5,
      'type': 'element',
      'itemParts': [],
      'blockParts': [],
      'ore': true
    },
    {
      'material': 'plutonium',
      'color': 0xbdabff,
      'itemParts': ['ingot', 'nugget', 'dust'],
      'blockParts': ['storage_block'],
      'fluid': 'thick'
    },
    {
      'material': 'neptunium',
      'color': 0x5a5863,
      'itemParts': ['dust'],
      'blockParts': [],
      'fluid': 'thick'
    },
    {
      'material': 'americium',
      'color': 0x4a3a2f,
      'itemParts': ['dust'],
      'blockParts': [],
      'fluid': 'thick'
    },
    {
      'material': 'curium',
      'color': 0x8a3e50,
      'itemParts': ['dust'],
      'blockParts': [],
      'fluid': 'thick'
    },
    {
      'material': 'berkelium',
      'color': 0x755444,
      'itemParts': ['dust'],
      'blockParts': [],
      'fluid': 'thick'
    },
    {
      'material': 'californium',
      'color': 0xc93328,
      'itemParts': ['dust'],
      'blockParts': [],
      'fluid': 'thick'
    },
    {
      'material': 'einsteinium',
      'color': 0x4a6da8,
      'itemParts': ['dust'],
      'blockParts': [],
      'fluid': 'thick'
    },
    {
      'material': 'oganesson',
      'color': 0x5f16a8,
      'itemParts': ['ingot', 'dust'],
      'blockParts': [],
      'fluid': 'thin'
    },
    {
      'material': 'radon',
      'color': 0x3fc217,
      'itemParts': ['ingot', 'dust'],
      'blockParts': [],
      'fluid': 'thin'
    },
    
    {
      'material': 'aerotheum',
      'color': 0xaea87c,
      'tier': 3,
      'type': 'alloy',
      'itemParts': ['custom_dust'],
      'blockParts': [],
      'dust_input': ['thermal:blitz_powder', '#forge:dusts/glowstone','cloudstorage:static_cloud', 'ars_nouveau:air_essence'],
      'amount': 2,
    },
    {
      'material': 'cryotheum',
      'color': 0x1fd0fa,
      'tier': 3,
      'type': 'alloy',
      'itemParts': ['custom_dust'],
      'blockParts': [],
      'dust_input': ['thermal:blizz_powder', '#forge:dusts/lapis', 'powah:charged_snowball', 'ars_nouveau:water_essence'],
      'amount': 2,
    },
    {
      'material': 'petrotheum',
      'color': 0x221915,
      'tier': 3,
      'type': 'alloy',
      'itemParts': ['custom_dust'],
      'blockParts': [],
      'dust_input': ['thermal:basalz_powder', '#forge:dusts/coal', '#forge:bitumen', 'ars_nouveau:earth_essence'],
      'amount': 2,
    },
    {
      'material': 'pyrotheum',
      'color': 0xfda735,
      'tier': 3,
      'type': 'alloy',
      'itemParts': ['custom_dust'],
      'blockParts': [],
      'dust_input': ['kubejs:blazing_redstone', '#forge:gems/sulfur', 'ars_nouveau:fire_essence'],
      'amount': 2,
    },
    {
      'material': 'plastic',
      'color': 0xe8e8e8,
      'itemParts': [],
      'blockParts': ['scaffolding']
    },
    /*
    {
      'material': 'blazing_redstone',
      'color': 0xd1482a,
      'tier': 1,
      'type': 'alloy',
      'itemParts': ['custom_dust'],
      'blockParts': [],
      'dust_input': ['minecraft:blaze_powder','#forge:dusts/redstone'],
      'amount': 1,
    },
    {
      'material': 'refined_iron',
      'color': 0xdbf5ff,
      'type': 'alloy',
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'gear', 'wire'],
      'blockParts': ['storage_block'],
      'fluid': 'thick',
    },
    {
      'material': 'crude_steel',
      'color': 0x6a7175,
      'type': 'alloy',
      'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'gear',],
      'blockParts': ['storage_block'],
      'fluid': 'thick',
    },
    {
      'material': 'thermalloy',
      'color': 0x8b4aed,
      'type': 'alloy',
      'tier': 1,
      'itemParts': ['ingot', 'nugget', 'rod', 'dust', 'plate', 'gear', 'wire', 'interlocking_component'],
      'blockParts': ['scaffolding','sheetmetal', 'cog_block','storage_block'],
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_thermalloy',
      'amount': 3,
      'dust_input': ['#forge:dusts/lumium','#forge:dusts/signalum','#forge:dusts/enderium'],
      'ingot_input': ['#forge:ingots/lumium','#forge:ingots/signalum','#forge:ingots/enderium'],
      'tinkers_input': [{tag: 'forge:molten_lumium',amount: 90},{tag: 'forge:molten_signalum',amount: 90},{tag: 'forge:molten_enderium',amount: 90}]
    },
    */
    
    /////////////// Gems /////////////////////////////
    /*
    {
      'material': 'ruby',
      'gem': true,
      'color': 0xff4f55,
      'type': 'gem',
      'itemParts': ['ruby', 'dust'],
      'blockParts': ['storage_block'],
      'ore': true
    },
    {
      'material': 'sapphire',
      'gem': true,
      'color': 0x7377ff,
      'type': 'gem',
      'itemParts': ['sapphire', 'dust'],
      'blockParts': ['storage_block'],
      'ore': true
    }*/
    {
      'material': 'certus_quartz',
      'gem': true,
      'color': 0xb7d8f7,
      'type': 'gem',
      'iconset': 'quartz',
      'itemParts': [],
      'blockParts': [],
      'ore': true
    },
    {
      'material': 'quartz',
      'gem': true,
      'color': 0xfff5e8,
      'type': 'gem',
      'iconset': 'quartz',
      'itemParts': [],
      'blockParts': [],
      'ore': true
    },
    {
      'material': 'diamond',
      'gem': true,
      'color': 0x42f5ef,
      'type': 'gem',
      'iconset': 'diamond',
      'itemParts': [],
      'blockParts': [],
      'ore': false
    },
    {
      'material': 'emerald',
      'gem': true,
      'color': 0x12b525,
      'type': 'gem',
      'iconset': 'emerald',
      'itemParts': [],
      'blockParts': [],
      'ore': false
    },
    {
      'material': 'fluix',
      'gem': true,
      'color': 0x6d168a,
      'type': 'gem',
      'iconset': 'quartz',
      'itemParts': [],
      'blockParts': [],
      'ore': false,
      'fluid': 'thick',
      'fluid_id': 'kubejs:molten_fluix',
    },
    ]
    
    global.stoneTypes = [
      {
        'material': 'deepslate',
        'hardness': 6,
        'resistance': 6
      },
      {
        'material': 'netherrack',
        'hardness': 3,
        'resistance': 3
      },
      {
        'material': 'tuff',
        'hardness': 3,
        'resistance': 3
      },
      {
        'material': 'smooth_basalt',
        'hardness': 3,
        'resistance': 3
      },
      {
        'material': 'basalt',
        'hardness': 3,
        'resistance': 3
      },
      {
        'material': 'blackstone',
        'hardness': 3,
        'resistance': 3
      },
      {
        'material': 'end_stone',
        'hardness': 4,
        'resistance': 4
      },
      {
        'material': 'darkstone',
        'hardness': 6,
        'resistance': 6
      },
      {
        'material': 'bedrock',
        'hardness': 10,
        'resistance': 10
      },/*
      {
        'material': 'soapstone',
        'hardness': 3,
        'resistance': 3
      },*/
      {
        'material': 'granite',
        'hardness': 3,
        'resistance': 3
      },
      {
        'material': 'diorite',
        'hardness': 3,
        'resistance': 3
      },
      {
        'material': 'andesite',
        'hardness': 3,
        'resistance': 3
      },
      {
        'material': 'moon_stone',
        'hardness': 4,
        'resistance': 4
      },
      {
        'material': 'mars_stone',
        'hardness': 4,
        'resistance': 4
      },
      {
        'material': 'venus_stone',
        'hardness': 4,
        'resistance': 4
      },
      {
        'material': 'glacio_stone',
        'hardness': 4,
        'resistance': 4
      }
    ]
