
#Settings for the mod's added generation
[world]

	[world.loot]
		#Add Lerasium to dungeon and other loot tables
		generate_lerasium = true
		#Add Unbreakable Obsidian Daggers to end city and other loot tables
		generate_unbreakable_daggers = true

	#Generation Settings for aluminum ore.
	[world.aluminum]
		#Enable aluminum generation
		generate = true
		#Density of aluminum Ore
		#Range: 1 ~ 40
		per_chunk = 14
		#Vein size of aluminum Ore
		#Range: 1 ~ 60
		size = 9
		#Whether aluminum is placed in a uniform block or triangular
		#Allowed Values: TRIANGLE, UNIFORM
		placement_type = "TRIANGLE"
		#Minimum Y Level to Generate aluminum
		#Range: -128 ~ 320
		min_y = 40
		#Maximum Y Level to Generatealuminum
		#Range: -64 ~ 512
		max_y = 120

	#Generation Settings for cadmium ore.
	[world.cadmium]
		#Enable cadmium generation
		generate = true
		#Density of cadmium Ore
		#Range: 1 ~ 40
		per_chunk = 5
		#Vein size of cadmium Ore
		#Range: 1 ~ 60
		size = 7
		#Whether cadmium is placed in a uniform block or triangular
		#Allowed Values: TRIANGLE, UNIFORM
		placement_type = "TRIANGLE"
		#Minimum Y Level to Generate cadmium
		#Range: -128 ~ 320
		min_y = -60
		#Maximum Y Level to Generatecadmium
		#Range: -64 ~ 512
		max_y = 0

	#Generation Settings for chromium ore.
	[world.chromium]
		#Enable chromium generation
		generate = true
		#Density of chromium Ore
		#Range: 1 ~ 40
		per_chunk = 8
		#Vein size of chromium Ore
		#Range: 1 ~ 60
		size = 6
		#Whether chromium is placed in a uniform block or triangular
		#Allowed Values: TRIANGLE, UNIFORM
		placement_type = "TRIANGLE"
		#Minimum Y Level to Generate chromium
		#Range: -128 ~ 320
		min_y = -30
		#Maximum Y Level to Generatechromium
		#Range: -64 ~ 512
		max_y = 30

	#Generation Settings for lead ore.
	[world.lead]
		#Enable lead generation
		generate = true
		#Density of lead Ore
		#Range: 1 ~ 40
		per_chunk = 15
		#Vein size of lead Ore
		#Range: 1 ~ 60
		size = 9
		#Whether lead is placed in a uniform block or triangular
		#Allowed Values: TRIANGLE, UNIFORM
		placement_type = "TRIANGLE"
		#Minimum Y Level to Generate lead
		#Range: -128 ~ 320
		min_y = -40
		#Maximum Y Level to Generatelead
		#Range: -64 ~ 512
		max_y = 30

	#Generation Settings for silver ore.
	[world.silver]
		#Enable silver generation
		generate = true
		#Density of silver Ore
		#Range: 1 ~ 40
		per_chunk = 11
		#Vein size of silver Ore
		#Range: 1 ~ 60
		size = 7
		#Whether silver is placed in a uniform block or triangular
		#Allowed Values: TRIANGLE, UNIFORM
		placement_type = "TRIANGLE"
		#Minimum Y Level to Generate silver
		#Range: -128 ~ 320
		min_y = -40
		#Maximum Y Level to Generatesilver
		#Range: -64 ~ 512
		max_y = 30

	#Generation Settings for tin ore.
	[world.tin]
		#Enable tin generation
		generate = true
		#Density of tin Ore
		#Range: 1 ~ 40
		per_chunk = 15
		#Vein size of tin Ore
		#Range: 1 ~ 60
		size = 11
		#Whether tin is placed in a uniform block or triangular
		#Allowed Values: TRIANGLE, UNIFORM
		placement_type = "TRIANGLE"
		#Minimum Y Level to Generate tin
		#Range: -128 ~ 320
		min_y = 30
		#Maximum Y Level to Generatetin
		#Range: -64 ~ 512
		max_y = 112

	#Generation Settings for zinc ore.
	[world.zinc]
		#Enable zinc generation
		generate = true
		#Density of zinc Ore
		#Range: 1 ~ 40
		per_chunk = 12
		#Vein size of zinc Ore
		#Range: 1 ~ 60
		size = 8
		#Whether zinc is placed in a uniform block or triangular
		#Allowed Values: TRIANGLE, UNIFORM
		placement_type = "TRIANGLE"
		#Minimum Y Level to Generate zinc
		#Range: -128 ~ 320
		min_y = 40
		#Maximum Y Level to Generatezinc
		#Range: -64 ~ 512
		max_y = 80

#Settings for the gameplay elements of the mod
[gameplay]
	#Spawn players as a random Misting
	random_mistings = true
	#Decides whether your spawn metal is based off your UUID (this will cause it to be consistent across worlds)
	respect_player_UUID = false

