#Range: 0 ~ 100
multiplier_iron = 10
#Range: 0 ~ 100
multiplier_steel = 10
#Range: 0 ~ 100
multiplier_tin = 10
#Range: 0 ~ 100
multiplier_pewter = 10
#Range: 0 ~ 100
multiplier_zinc = 10
#Range: 0 ~ 100
multiplier_brass = 10
#Range: 0 ~ 100
multiplier_copper = 25
#Range: 0 ~ 100
multiplier_bronze = 10
#Range: 0 ~ 100
multiplier_aluminum = 10
#Range: 0 ~ 100
multiplier_duralumin = 10
#Range: 0 ~ 100
multiplier_chromium = 10
#Range: 0 ~ 100
multiplier_nicrosil = 10
#Range: 0 ~ 100
multiplier_gold = 10
#Range: 0 ~ 100
multiplier_electrum = 10
#Range: 0 ~ 100
multiplier_cadmium = 10
#Range: 0 ~ 100
multiplier_bendalloy = 10
#1: all feruchemy; 0: random
#Range: 0 ~ 1
starting_power = 0
#Restrict access to zinc/bronze Feruchemy
server_restrict = false
#if true makes powers consistent across worlds based off of uuid
respect_uuid = false
#start cost of tapping
#Range: 0 ~ 9999999
tapping_start_cost = 1

